Repository hmcts/cnp-plum-recipes-service, pull requests merged in 2020-06, with the labels that each got.

#133 Add helm requirements renovate
  .github/renovate.json
Labels: ns:cnp, rel:plum-recipe-backend-pr-133

#135 Add gradlew for renovate
  .github/renovate.json
Labels: ns:cnp, rel:plum-recipe-backend-pr-135

#137 Upgrade helm charts
  charts/crumble-recipe-backend/Chart.yaml
  charts/crumble-recipe-backend/requirements.yaml
  charts/plum-recipe-backend/Chart.yaml
  charts/plum-recipe-backend/requirements.yaml
Labels: ns:cnp, rel:plum-recipe-backend-pr-137

#143 U878 plum api tf
  infrastructure/main.tf
  infrastructure/template/api.json
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-143

#144 fix missing git
  infrastructure/main.tf
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-144

#145 syntax correction from / to : using git clone
  infrastructure/main.tf
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-145

#146 update api mgmt api
  infrastructure/main.tf
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-146

#147 update json
  .github/workflows/swagger.yaml
  build.gradle
  config/pmd/ruleset.xml
  infrastructure/main.tf
  src/test/java/uk/gov/hmcts/reform/rhubarb/recipes/SwaggerPublisher.java
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-147

#149 Use Junit 5 , fixing swagger publish
  .github/workflows/swagger.yaml
  build.gradle
  config/pmd/ruleset.xml
  src/main/java/uk/gov/hmcts/reform/rhubarb/recipes/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/rhubarb/recipes/endpoint/EndpointExceptionHandler.java
  src/test/functional/java/uk/gov/hmcts/reform/rhubarb/functional/HealthCheckTest.java
  src/test/functional/java/uk/gov/hmcts/reform/rhubarb/functional/RecipesTest.java
  src/test/gateway/java/uk/gov/hmcts/reform/rhubarb/api/GetAllRecipesTest.java
  src/test/java/uk/gov/hmcts/reform/rhubarb/recipes/ApplicationTests.java
  src/test/java/uk/gov/hmcts/reform/rhubarb/recipes/SwaggerPublisher.java
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-149

#150 remove unused property
  src/main/java/uk/gov/hmcts/reform/rhubarb/recipes/endpoint/RecipeController.java
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-150

#151 add thumbprint
  infrastructure/main.tf
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-151
