Repository hmcts/cnp-plum-recipes-service, pull requests merged in 2021-06, with the labels that each got.

#347 adaptation of highLevelDataSetup
  build.gradle
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-347

#352 Upgrade springboot version to fix cve-2021-22118 vulnerabilities
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-352

#353 Upgrade terraform version to 1.0.0
  infrastructure/.terraform-version
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-353
