Repository hmcts/cnp-plum-recipes-service, pull requests merged in 2022-06, with the labels that each got.

#507 DTSPO-8276 - Fix security checks
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-507

#509 DTSPO-8276 - Fix security checks
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-509

#518 Test java chart upgrades
  charts/crumble-recipe-backend/Chart.yaml
  charts/plum-recipe-backend/Chart.yaml
  charts/plum-recipe-backend/values.preview.template.yaml
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-518
