Repository hmcts/cnp-plum-recipes-service, pull requests merged in 2022-07, with the labels that each got.

#520 Update dependency-check-suppressions.xml
  dependency-check-suppressions.xml
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-520

#522 Update Chart.yaml
  charts/plum-recipe-backend/Chart.yaml
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-522

#531 Suppress CVE
  dependency-check-suppressions.xml
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-531
