Repository hmcts/cnp-plum-recipes-service, pull requests merged in 2023-04, with the labels that each got.

#720 DTSPO-11734 - renovate - add schema
  .github/renovate.json
Labels: chore

#724 DTSPO-13333 adding postgresql flexible server to plum
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:cnp, prd:plum, add-or-update, rel:plum-recipe-backend-pr-724

#731 Update main.tf
  infrastructure/main.tf
Labels: ns:cnp, prd:plum, no-changes, rel:plum-recipe-backend-pr-731

#734 Update main.tf
  infrastructure/main.tf
Labels: ns:cnp, prd:plum, add-or-update, rel:plum-recipe-backend-pr-734

#735 DTSPO-13245 Updating access to postgres flexserver
  charts/plum-recipe-backend/Chart.yaml
  charts/plum-recipe-backend/values.yaml
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-735

#737 DTSPO-13332 - Update dependency management plugin
  build.gradle
Labels: ns:cnp, prd:plum, rel:plum-recipe-backend-pr-737

#738 DTSPO-13245 Removing v11 postgres
  infrastructure/main.tf
Labels: ns:cnp, prd:plum, destroy, rel:plum-recipe-backend-pr-738
